# Generated by Django 4.2.4 on 2023-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by_user_id', models.IntegerField()),
                ('file_name', models.TextField()),
                ('upload_path', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('new_file', models.BooleanField(default=True)),
                ('check_result', models.TextField(null=True)),
                ('check_log', models.TextField(null=True)),
            ],
        ),
    ]
